#Intro to Python for Data Science

#Ch.3 Functions and Packages

##List Methods

In [10]:
# Create list areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Print out the index of the element 20.0
print(areas.index(20.0))

# Print out how often 14.5 appears in areas
print(areas.count(14.5))

2
0


In [11]:
# Create list areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Use append twice to add poolhouse and garage size
areas.append(24.5)
areas.append(15.45)

# Print out areas
print(areas)

# Reverse the orders of the elements in areas
areas.reverse()

# Print out areas
print(areas)

[11.25, 18.0, 20.0, 10.75, 9.5, 24.5, 15.45]
[15.45, 24.5, 9.5, 10.75, 20.0, 18.0, 11.25]


##Import Package

In [12]:
# Definition of radius
r = 0.43

# Import the math package
import math

# Calculate C
C = 2 * math.pi * r

# Calculate A
A = math.pi * r**2

# Build printout
print("Circumference: " + str(C))
print("Area: " + str(A))

Circumference: 2.70176968209
Area: 0.580880481649


##Selective Import

In [13]:
# Definition of radius
r = 192500

# Import radians function of math package
from math import radians

# Travel distance of Moon if 12 degrees. Store in dist.
dist = r * radians(12)

# Print out dist
print(dist)

40317.1057211


##Different Ways of Importing

In [14]:
from scipy.linalg import inv as my_inv

In [15]:
my_inv([[1,2], [3,4]])

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

#Ch.4 Numpy

##Your First Numpy Array

In [16]:
# Create list baseball 
baseball = [180, 215, 210, 210, 188, 176, 209, 200]

# Import the numpy package as np
import numpy as np

# Create a Numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out type of np_baseball
print(type(np_baseball))

<type 'numpy.ndarray'>


##Baseball Players' Height

In [17]:
# height is available as a regular list
height = [200, 190, 195, 210, 205]

# Import numpy
import numpy as np

# Create a Numpy array from height: np_height
np_height = np.array(height)

# Print out np_height
print(np_height)

# Convert np_height to m: np_height_m
np_height_m = np_height * 0.0254

# Print np_height_m
print(np_height_m)

[200 190 195 210 205]
[ 5.08   4.826  4.953  5.334  5.207]


##Baseball Players' BMI

In [18]:
# height and weight are available as a regular lists
weight = [200, 190, 195, 210, 205]

# Import numpy
import numpy as np

# Create array from height with correct units: np_height_m
np_height_m = np.array(height) * 0.0254

# Create array from weight with correct units: np_weight_kg 
np_weight_kg = np.array(weight) * 0.453592

# Calculate the BMI: bmi
bmi = np_weight_kg / np_height_m**2

# Print out bmi
print(bmi)

[ 3.51534503  3.70036319  3.60548208  3.34794765  3.42960491]


##Lightweight Baseball Players

In [19]:
# height and weight are available as a regular lists

# Import numpy
import numpy as np

# Calculate the BMI: bmi
np_height_m = np.array(height) * 0.0254
np_weight_kg = np.array(weight) * 0.453592
bmi = np_weight_kg / np_height_m ** 2

# Create the light array
light = bmi < 21

# Print out light
print(light)

# Print out BMIs of all baseball players whose BMI is below 21
print(bmi[light])

[ True  True  True  True  True]
[ 3.51534503  3.70036319  3.60548208  3.34794765  3.42960491]


##Subsetting Numpy Arrays

In [21]:
# height and weight are available as a regular lists

# Import numpy
import numpy as np

# Store weight and height lists as numpy arrays
np_weight = np.array(weight)
np_height = np.array(height)

# Print out the weight at index 1
print(np_weight[1])

# Print out sub-array of np_height: index 1 up to and including index 3
print(np_height[1:4])

190
[190 195 210]


##Your First 2D Numpy Array

In [22]:
# Create baseball, a list of lists
baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]

# Import numpy
import numpy as np

# Create a 2D Numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out the type of np_baseball
print(type(np_baseball))

# Print out the shape of np_baseball
print(np_baseball.shape)

<type 'numpy.ndarray'>
(4, 2)


##Subsetting 2D Numpy Arrays

In [23]:
# baseball is available as a regular list of lists

# Import numpy package
import numpy as np

# Create np_baseball (2 cols)
np_baseball = np.array(baseball)

# Print out the 3rd row of np_baseball
print(np_baseball[2, :])

# Select the entire second column of np_baseball: np_weight
np_weight = np_baseball[:, 1]

# Print out height of 4th player
print(np_baseball[3, 0])

[ 210.    98.5]
188.0


##2D Arithmetic

In [29]:
import numpy as np
np_mat = np.array([[1, 2],
                   [3, 4],
                   [5, 6]])
np_mat * 2

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [30]:
np_mat + np.array([10, 10])

array([[11, 12],
       [13, 14],
       [15, 16]])

In [31]:
np_mat + np_mat

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [39]:
# baseball is available as a regular list of lists
# update is available as 2D Numpy array
baseball = [[1,2,3],[4,5,6],[7,8,9],[10,11,12]]
update = np.array([[1,2,10],[3,4,20],[5,6,30],[7,8,40]])

# Import numpy package
import numpy as np

# Create np_baseball (3 cols)
np_baseball = np.array(baseball)

# Print out addition of np_baseball and update
print(np_baseball + update)

# Create Numpy array: conversion
conversion = np.array([0.0254, 0.453592, 1])

# Print out product of np_baseball and conversion
print(np_baseball * conversion)

[[ 2  4 13]
 [ 7  9 26]
 [12 14 39]
 [17 19 52]]
[[  0.0254     0.907184   3.      ]
 [  0.1016     2.26796    6.      ]
 [  0.1778     3.628736   9.      ]
 [  0.254      4.989512  12.      ]]


##Average versus Median

In [40]:
# np_baseball is available
# 1015 rows x 3 columns (height, weight, age)

# Import numpy
import numpy as np

# Create np_height from np_baseball
np_height = np_baseball[:,0]

# Print out the mean of np_height
print(np.mean(np_height))

# Print out the median of np_height
print(np.median(np_height))

5.5
5.5


##Explore the Baseball Data

In [41]:
# np_baseball is available

# Import numpy
import numpy as np

# Print mean height (first column)
avg = np.mean(np_baseball[:,0])
print("Average: " + str(avg))

# Print median height. Replace 'None'
med = np.median(np_baseball[:,0])
print("Median: " + str(med))

# Print out the standard deviation on height. Replace 'None'
stddev = np.std(np_baseball[:,0])
print("Standard Deviation: " + str(stddev))

# Print out correlation between first and second column. Replace 'None'
corr = np.corrcoef(np_baseball[:,0], np_baseball[:,1])
print("Correlation: " + str(corr))

Average: 5.5
Median: 5.5
Standard Deviation: 3.35410196625
Correlation: [[ 1.  1.]
 [ 1.  1.]]


##Blend It All Together

In [42]:
# heights and positions are available as lists
positions = ['GK', 'M', 'A', 'D']
heights = [191, 184, 185, 180]

# Import numpy
import numpy as np

# Convert positions and heights to numpy arrays: np_positions, np_heights
np_positions = np.array(positions)
np_heights = np.array(heights)

# Heights of the goalkeepers: gk_heights
gk_heights = np_heights[np_positions == 'GK']

# Heights of the other players: other_heights
other_heights = np_heights[np_positions != 'GK']

# Print out the median height of goalkeepers. Replace 'None'
print("Median height of goalkeepers: " + str(np.median(gk_heights)))

# Print out the median height of other players. Replace 'None'
print("Median height of other players: " + str(np.median(other_heights)))

Median height of goalkeepers: 191.0
Median height of other players: 184.0
